import numpy as np
import ROOT as rt

sample_configurables = {
#'SMS-T2bW_dM' : {
#  'legend' : 'SMS-T2bW',
#  'color'  : rt.kMagenta-4,
#  'style'  : 1,
#  'width'  : 3,
#  'fill'  : None,
#  'fill_style'  : None,
#             },
#'SMS-T2tt_dM' : {
#  'legend' : 'SMS-T2tt',
#  'color'  : rt.kMagenta+4,
#  'style'  : 1,
#  'width'  : 3,
#  'fill'  : None,
#  'fill_style'  : None,
#             },
'SMS-T2-4bd_490' : {
  'legend' : 'SMS-T2-4bd',
  'color'  : rt.kViolet-5,
  'style'  : 1,
  'width'  : 3,
  'fill'  : None,
  'fill_style'  : None,
             },
'SMS-T2-4bd_420' : {
  'legend' : 'SMS-T2-4bd',
  'color'  : rt.kViolet+5,
  'style'  : 1,
  'width'  : 3,
  'fill'  : None,
  'fill_style'  : None,
             },
'TTJets_2017'   : {
  'legend' : 't#bar{t}+jets',
  'color'  : rt.kBlue+1,
  'style'  : 1,
  'width'  : 3,
  'fill'   : rt.kBlue+1,
  'fill_style'   : 1001,
             },
'WJets_2017'   : {
  'legend' : 'W+jets',
  'color'  : rt.kRed+1,
  'style'  : 1,
  'width'  : 3,
  'fill'   : rt.kRed+1,
  'fill_style'   : 1001,
             },
'ZJets_2017'   : {
  'legend' : 'Z+jets',
  'color'  : rt.kYellow+1,
  'style'  : 1,
  'width'  : 3,
  'fill'   : rt.kYellow+1,
  'fill_style'   : 1001,
             },
'DY_M50_2017'   : {
  'legend' : 'DY+jets',
  'color'  : rt.kGreen+1,
  'style'  : 1,
  'width'  : 3,
  'fill'   : rt.kGreen+1,
  'fill_style'   : 1001,
             },
'WW_2017'   : {
  'legend' : 'WW',
  'color'  : rt.kCyan+1,
  'style'  : 1,
  'width'  : 3,
  'fill'   : rt.kCyan+1,
  'fill_style'   : 1001,
             },
'ZZ_2017'   : {
  'legend' : 'ZZ',
  'color'  : rt.kCyan-1,
  'style'  : 1,
  'width'  : 3,
  'fill'   : rt.kCyan-1,
  'fill_style'   : 1001,
             },
'WZ_2017'   : {
  'legend' : 'WZ',
  'color'  : rt.kCyan-9,
  'style'  : 1,
  'width'  : 3,
  'fill'   : rt.kCyan-9,
  'fill_style'   : 1001,
             },
}

######   configuration template   ######
"""
'Null'    : {
  'xlabel'  : None,
  'ylabel'  : None,
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : False,
              },
"""
######  end template  ######
plot_configurables = {
'NS_SVs'    : {
  'xlabel'  : 'N S SVs',
  'ylabel'  : 'Events',
  'nbins_x' : None,
  'xmin'    : 0.,
  'xmax'    : 8.,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'NISR_SVs'    : {
  'xlabel'  : 'N ISR SVs',
  'ylabel'  : 'Events',
  'nbins_x' : None,
  'xmin'    : 0.,
  'xmax'    : 8.,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'PT_SV'    : {
  'xlabel'  : 'p_{T} SVs',
  'ylabel'  : 'Events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'NS_jets'    : {
  'xlabel'  : 'N S jets',
  'ylabel'  : 'Events',
  'nbins_x' : None,
  'xmin'    : 0,
  'xmax'    : 8,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'NS_STs'    : {
  'xlabel'  : 'N S STs',
  'ylabel'  : 'Events',
  'nbins_x' : None,
  'xmin'    : 0,
  'xmax'    : 8,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'NS_SBs'    : {
  'xlabel'  : 'N S (SVs + bjets)',
  'ylabel'  : 'Events',
  'nbins_x' : None,
  'xmin'    : 0,
  'xmax'    : 8,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'NISR_bjets'    : {
  'xlabel'  : 'N ISR bjets',
  'ylabel'  : 'Events',
  'nbins_x' : None,
  'xmin'    : 0,
  'xmax'    : 8,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'MET'    : {
  'xlabel'  : 'E_{T}^{miss} [GeV]',
  'ylabel'  : 'Events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'MET_postrisr'    : {
  'xlabel'  : 'E_{T}^{miss} [GeV]',
  'ylabel'  : 'Events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'MS'    : {
  'xlabel'  : 'M_{S} [GeV]',
  'ylabel'  : 'Events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'MS_preisrb'    : {
  'xlabel'  : 'M_{S} pre 0 isrb cut [GeV]',
  'ylabel'  : 'Events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'MS_prest'    : {
  'xlabel'  : 'M_{S} pre s-object cut [GeV]',
  'ylabel'  : 'Events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'RISR_PTISR'    : {
  'xlabel'  : 'R_{ISR} [GeV]',
  'ylabel'  : 'p_{T}^{ISR} [GeV]',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'RISR_PTISR_prest'    : {
  'xlabel'  : 'R_{ISR} pre s-object cut [GeV]',
  'ylabel'  : 'p_{T}^{ISR} pre s-object cut [GeV]',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'RISR_PTISR_preisrb'    : {
  'xlabel'  : 'R_{ISR} pre 0 isrb cut [GeV]',
  'ylabel'  : 'p_{T}^{ISR} pre 0 isrb cut [GeV]',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'RISR_PTISR_postscut'    : {
  'xlabel'  : 'R_{ISR} full selection [GeV]',
  'ylabel'  : 'p_{T}^{ISR} full selection [GeV]',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'PzS_div_PTISR'    : {
  'xlabel'  : 'p_{z}^{S} / (p_{z}^{S} + p_{T}^{ISR})',
  'ylabel'  : 'Events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'PTS_div_PTISR'    : {
  'xlabel'  : 'p_{T}^{S} / (p_{T}^{S} + p_{T}^{ISR})',
  'ylabel'  : 'Events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'dphi_lep_MET'    : {
  'xlabel'  : '#Delta #phi(lead lep, E_{T}^{miss})',
  'ylabel'  : 'Events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'dphi_lep_S'    : {
  'xlabel'  : '#Delta #phi_{l, S}',
  'ylabel'  : 'Events',
  'nbins_x' : None,
  'xmin'    : 0.,
  'xmax'    : np.pi,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'cos_lep_S'    : {
  'xlabel'  : 'Cos(l, S)',
  'ylabel'  : 'Events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'MLL'    : {
  'xlabel'  : 'M_{ll} [GeV]',
  'ylabel'  : 'Events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
'dphi_ll'    : {
  'xlabel'  : '#Delta #phi_{ll}',
  'ylabel'  : 'Events',
  'nbins_x' : None,
  'xmin'    : None,
  'xmax'    : None,
  'nbinsy'  : None,
  'ymin'    : None,
  'ymax'    : None,
  'log'     : True,
              },
}
